export type WorkType = "Fractional" | "Part-time" | "Contract";
export type Seniority = "Mid-level" | "Senior" | "Not specified";
export type BenefitType = "Healthcare" | "Retirement" | "Paid time off" | "Paid leave";
export type BenefitDisclosure = "listed" | "none" | "not-disclosed";

export type Job = {
  id: string;
  company: string;
  initials: string;
  accent: string;
  role: string;
  category: string;
  location: string;
  collaboration: string;
  scheduleText: string;
  hoursMin: number | null;
  hoursMax: number | null;
  compensation: string;
  workType: WorkType;
  seniority: Seniority;
  duration: string;
  posted: string;
  crawledAt: string;
  sourceName: string;
  sourceUrl: string;
  summary: string;
  expectations: string[];
  benefitTypes: BenefitType[];
  benefitDisclosure: BenefitDisclosure;
  benefits: string[];
  tags: string[];
};

export const jobs: Job[] = [
  {
    id: "yor-ai-devops",
    company: "YOR.AI",
    initials: "YA",
    accent: "#b9ef68",
    role: "Part-Time DevOps & Backend Engineer",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Daily communication; listing names 9:01 a.m.–5:01 p.m. PT as collaboration hours",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$70–$80 / hour",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "~6 weeks through Aug. 15; extension possible",
    posted: "Posted 3 weeks ago",
    crawledAt: "July 19, 2026",
    sourceName: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs/4362035-part-time-devops-backend-engineer",
    summary: "A hands-on 1099 engagement in an existing AI codebase, working directly with the co-founder and lead engineer on client delivery.",
    expectations: [
      "Manage infrastructure for production AI systems",
      "Debug and improve an existing RAG system",
      "Maintain Postgres and vector databases and document fixes",
    ],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["1099 contract", "Employer benefits are not listed", "No equity"],
    tags: ["Python", "DevOps", "RAG", "Postgres"],
  },
  {
    id: "form-ai-engineer",
    company: "Form AI",
    initials: "FA",
    accent: "#7dd3fc",
    role: "Fractional Software Engineer",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Client-facing work; Central Time preferred; most communication is written",
    scheduleText: "10–20 hrs / week",
    hoursMin: 10,
    hoursMax: 20,
    compensation: "$75–$150 / hour",
    workType: "Fractional",
    seniority: "Mid-level",
    duration: "Monthly minimum of 40 hours; scales by agreement",
    posted: "Posted 2 months ago",
    crawledAt: "July 19, 2026",
    sourceName: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs/4163009-software-engineer",
    summary: "A 1099 builder role for client-facing AI applications, spanning product scoping, full-stack implementation, integrations, and LLM systems.",
    expectations: [
      "Scope each engagement alongside the client",
      "Ship end-to-end applications that clients actually use",
      "Build front ends, back ends, integrations, and LLM-heavy workflows",
    ],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["1099 contract", "Employer benefits are not listed", "Paid monthly"],
    tags: ["Python", "TypeScript", "React", "Generative AI"],
  },
  {
    id: "cars-bids-data",
    company: "Cars & Bids",
    initials: "CB",
    accent: "#fe7d62",
    role: "Senior Data Engineer — Fractional",
    category: "Data",
    location: "Remote · United States",
    collaboration: "Five-hour overlap with PT working hours; contractor sets schedule and tools",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$80–$120 / hour",
    workType: "Fractional",
    seniority: "Senior",
    duration: "Ongoing monthly retainer",
    posted: "Listed this week",
    crawledAt: "July 19, 2026",
    sourceName: "Indeed",
    sourceUrl: "https://www.indeed.com/viewjob?jk=f9f7455d1778c9b8",
    summary: "The sole dedicated data practitioner owns the stack from ingestion through Snowflake, modeling, inference, and reverse ETL.",
    expectations: [
      "Own the full data lifecycle and running health of the stack",
      "Keep pipelines, models, and operational syncs reliable",
      "Manage Snowflake cost discipline and resolve data quality issues at the root",
    ],
    benefitTypes: [],
    benefitDisclosure: "none",
    benefits: ["No company benefits or equity", "Contractor supplies equipment and insurance", "1099/B2B monthly retainer"],
    tags: ["Snowflake", "SQL", "Reverse ETL", "Data quality"],
  },
  {
    id: "dg-data-engineer",
    company: "D&G Support Services",
    initials: "DG",
    accent: "#c4b5fd",
    role: "Data Engineer — Part Time",
    category: "Data",
    location: "Remote · United States",
    collaboration: "Works across government stakeholders, operators, engineers, and designers; active Secret clearance required",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "$60–$67 / hour",
    workType: "Part-time",
    seniority: "Senior",
    duration: "Not stated",
    posted: "Listed 1 week ago",
    crawledAt: "July 19, 2026",
    sourceName: "Migrate Mate",
    sourceUrl: "https://migratemate.co/companies-hiring/d-g-support-services-llc",
    summary: "A mission and systems architecture role connecting operational requirements, data strategy, modeling, and implementation roadmaps for defense clients.",
    expectations: [
      "Develop mission architecture frameworks and implementation roadmaps",
      "Document systems, data flows, interfaces, and technical risks",
      "Produce client-ready architecture products and executive briefings",
    ],
    benefitTypes: ["Retirement", "Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["401(k), PTO, education reimbursement and profit sharing are listed", "Flexible hours are listed", "Eligibility thresholds are not stated"],
    tags: ["Systems architecture", "MBSE", "Data flows", "Secret clearance"],
  },
  {
    id: "hii-sentiment-advisor",
    company: "HII Mission Technologies",
    initials: "HI",
    accent: "#f9c74f",
    role: "Military Advisor — Data Science / Sentiment Analysis",
    category: "Data",
    location: "Remote · United States; substantial travel",
    collaboration: "51–75% episodic OCONUS travel; ability to obtain a Secret clearance",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "$90 / hour",
    workType: "Part-time",
    seniority: "Senior",
    duration: "Not stated",
    posted: "Posted 11 days ago",
    crawledAt: "July 19, 2026",
    sourceName: "DailyRemote",
    sourceUrl: "https://dailyremote.com/remote-job/military-advisor-data-science-sentiment-analysis-part-time-remote-mission-assurance-4-29181-5263063",
    summary: "A senior technical and educator role delivering sentiment-analysis frameworks, training, data collection, and intelligence products for DoD missions.",
    expectations: [
      "Design sentiment-analysis frameworks and advise on tools",
      "Develop and deliver training for DoD personnel",
      "Process multi-source data and brief leadership on trends and threats",
    ],
    benefitTypes: ["Healthcare", "Retirement", "Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["Medical, dental and vision plan choices are listed", "401(k), paid holidays, PTO and tuition reimbursement are listed", "Eligibility thresholds are not stated"],
    tags: ["NLP", "Python", "OSINT", "Data visualization"],
  },
  {
    id: "nadia-care-ux",
    company: "Nadia Care",
    initials: "NC",
    accent: "#fb7185",
    role: "Contract UX Researcher",
    category: "Design",
    location: "Remote · Contiguous United States",
    collaboration: "Occasional calls with product and care teams; weekly interviews with members and care staff",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$50–$80 / hour",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "~4 months; extension possible",
    posted: "Listed this week",
    crawledAt: "July 19, 2026",
    sourceName: "Greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/nadiacare/jobs/4306881009",
    summary: "A bounded Q3 research engagement focused on member interviews, personas, product friction, and early retention signals in maternal healthcare.",
    expectations: [
      "Design the interview guide and member outreach strategy",
      "Conduct member interviews every week",
      "Deliver personas, friction findings, and actionable retention signals",
    ],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["The posting describes benefits for full-time employees", "Contract-role eligibility is not stated", "Four-stage interview process is disclosed"],
    tags: ["UX research", "Healthcare", "Interviews", "Personas"],
  },
  {
    id: "serious-development-design",
    company: "Serious Development",
    initials: "SD",
    accent: "#5eead4",
    role: "Fractional Product Systems Designer",
    category: "Design",
    location: "Remote · United States",
    collaboration: "Review-heavy role embedded early with PMs and engineers; code and prototypes are the source of truth",
    scheduleText: "20–30 hrs / month",
    hoursMin: null,
    hoursMax: null,
    compensation: "Competitive hourly rate; amount not disclosed",
    workType: "Fractional",
    seniority: "Senior",
    duration: "Long-term if mutually successful",
    posted: "Listed this month",
    crawledAt: "July 19, 2026",
    sourceName: "Breezy",
    sourceUrl: "https://serious-development.breezy.hr/p/33118b09b763-fractional-product-systems-designer-web-ios-remote-u-s-based",
    summary: "A systems-level UX ownership role defining product behavior and platform consistency rather than producing every screen or maintaining Figma parity.",
    expectations: [
      "Own interaction patterns and reduce UX drift across modules",
      "Define behavioral standards for Angular and PrimeNG components",
      "Keep native iOS interactions aligned with platform conventions",
    ],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "Compensation amount is not disclosed", "Long-term engagement is possible"],
    tags: ["Systems design", "iOS", "Angular", "PrimeNG"],
  },
  {
    id: "pear-suite-security",
    company: "Pear Suite",
    initials: "PS",
    accent: "#f0abfc",
    role: "IT & Security Analyst",
    category: "Security",
    location: "Remote · United States",
    collaboration: "Works closely with the CTO in a hands-on, audit-ready healthcare SaaS environment",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$45–$50 / hour",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "Not stated",
    posted: "Posted 4 days ago",
    crawledAt: "July 19, 2026",
    sourceName: "Rippling",
    sourceUrl: "https://ats.rippling.com/pear-suites-career-page/jobs/b7826aee-f42d-4ef2-b55d-19437538ed14",
    summary: "A tactical security and internal IT role supporting healthcare compliance, access controls, audits, device management, and incident procedures.",
    expectations: [
      "Maintain HITRUST, HIPAA, and SOC 2 compliance work",
      "Run risk assessments and gather evidence for audits",
      "Manage access, devices, onboarding, offboarding, and vendor reviews",
    ],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "Geographic pay adjustments may apply", "Approximate weekly capacity is stated"],
    tags: ["HIPAA", "SOC 2", "HITRUST", "GCP"],
  },
];
