import rawJobs from "../data/jobs.json";

export type WorkType = "Fractional" | "Part-time" | "Contract";
export type Seniority = "Entry-level" | "Mid-level" | "Senior" | "Not specified";
export type BenefitType = "Healthcare" | "Retirement" | "Paid time off" | "Paid leave";
export type BenefitDisclosure = "listed" | "none" | "not-disclosed";
export type JobStatus = "active" | "review" | "closed";

export type Job = {
  id: string;
  company: string;
  initials: string;
  accent: string;
  role: string;
  category: string;
  location: string;
  collaboration: string;
  scheduleText: string;
  hoursMin: number | null;
  hoursMax: number | null;
  compensation: string;
  hourlyPayMin: number | null;
  hourlyPayMax: number | null;
  hourlyPayIsEstimate: boolean;
  hourlyPayComparable?: boolean;
  payCurrency?: string | null;
  hourlyPayNote: string;
  workType: WorkType;
  seniority: Seniority;
  duration: string;
  postedDate: string;
  postedDateIsEstimate: boolean;
  lastVerifiedDate: string;
  sourceUpdatedDate?: string | null;
  sourceName: string;
  sourceUrl: string;
  applyUrl?: string;
  summary: string;
  expectations: string[];
  benefitTypes: BenefitType[];
  benefitDisclosure: BenefitDisclosure;
  benefits: string[];
  tags: string[];
  sourceKind: string;
  sourceTenant: string;
  sourceJobId: string;
  sourceTier?: "primary" | "aggregator";
  status: JobStatus;
  firstSeenAt: string;
  lastSeenAt: string;
  lastChangedAt: string;
  closedAt?: string;
  contentHash: string;
  consecutiveMisses: number;
  curated: boolean;
};

export const allJobs = rawJobs as unknown as Job[];
export const jobs = allJobs.filter((job) => job.status === "active");
