export type WorkType = "Fractional" | "Part-time" | "Contract";
export type Seniority = "Entry-level" | "Mid-level" | "Senior" | "Not specified";
export type BenefitType = "Healthcare" | "Retirement" | "Paid time off" | "Paid leave";
export type BenefitDisclosure = "listed" | "none" | "not-disclosed";

export type Job = {
  id: string;
  company: string;
  initials: string;
  accent: string;
  role: string;
  category: string;
  location: string;
  collaboration: string;
  scheduleText: string;
  hoursMin: number | null;
  hoursMax: number | null;
  compensation: string;
  hourlyPayMin: number | null;
  hourlyPayMax: number | null;
  hourlyPayIsEstimate: boolean;
  hourlyPayNote: string;
  workType: WorkType;
  seniority: Seniority;
  duration: string;
  postedDate: string;
  postedDateIsEstimate: boolean;
  lastVerifiedDate: string;
  sourceName: string;
  sourceUrl: string;
  summary: string;
  expectations: string[];
  benefitTypes: BenefitType[];
  benefitDisclosure: BenefitDisclosure;
  benefits: string[];
  tags: string[];
};

const checked = "2026-07-19";

export const jobs: Job[] = [
  {
    id: "upstatement-support-engineer",
    company: "Upstatement / Core Functions",
    initials: "UP",
    accent: "#b9ef68",
    role: "Full Stack Support Engineer (Contractor)",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Approximately 20 hours each week with availability during 9 a.m.–5 p.m. Eastern",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$50–$75 / hour",
    hourlyPayMin: 50,
    hourlyPayMax: 75,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range.",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "3–6 months; extension possible",
    postedDate: "2026-07-12",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/upstatementrecruiting/jobs/6100661004",
    summary: "A maintenance and enhancement role across mission-driven websites, working within a small senior web-services team.",
    expectations: ["Ship enhancements, fixes, and updates", "Work across JavaScript, PHP, CMSs, performance, and accessibility"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Independent contractor engagement", "Employer benefits are not listed"],
    tags: ["JavaScript", "PHP", "WordPress", "Accessibility"],
  },
  {
    id: "careacross-django",
    company: "CareAcross",
    initials: "CA",
    accent: "#7dd3fc",
    role: "Python / Django Software Engineer",
    category: "Engineering",
    location: "Remote · Greece",
    collaboration: "Flexible schedule with the Development and Product teams",
    scheduleText: "15–25 hrs / week",
    hoursMin: 15,
    hoursMax: 25,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "May convert to full-time by mutual agreement",
    postedDate: "2026-07-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Workable",
    sourceUrl: "https://apply.workable.com/careacross/j/9CFFCE25FA/",
    summary: "Build patient applications, clinician dashboards, monitoring workflows, integrations, and analytics for cancer-care products.",
    expectations: ["Develop Python and Django services", "Collaborate on product and technical decisions"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Fully remote and flexible scheduling are listed", "Healthcare and retirement benefits are not disclosed"],
    tags: ["Python", "Django", "PostgreSQL", "Digital health"],
  },
  {
    id: "implicit-ai-engineer",
    company: "Implicit",
    initials: "IM",
    accent: "#c4b5fd",
    role: "Applied AI Engineer",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Flexible part-time schedule with product, engineering, and data science",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer describes compensation as competitive but publishes no amount.",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "Not stated",
    postedDate: "2026-07-01",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/implicit/jobs/8039713",
    summary: "Build production AI knowledge systems for maintenance and support, including RAG, search, document ingestion, and agents.",
    expectations: ["Develop production AI services in Python", "Improve retrieval quality and evaluation systems"],
    benefitTypes: ["Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["Flexible vacation policy is listed", "Healthcare and retirement benefits are not disclosed"],
    tags: ["LLMs", "RAG", "Python", "MLOps"],
  },
  {
    id: "parsley-growth-pm",
    company: "Parsley Health",
    initials: "PH",
    accent: "#fe7d62",
    role: "Fractional Growth Product Manager",
    category: "Product",
    location: "Remote · United States preferred",
    collaboration: "Weekly written update, one 30-minute working session, and reasonable async collaboration",
    scheduleText: "~10 hrs / week",
    hoursMin: 10,
    hoursMax: 10,
    compensation: "$75–$200 / hour",
    hourlyPayMin: 75,
    hourlyPayMax: 200,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range; no minimum hours guaranteed.",
    workType: "Fractional",
    seniority: "Senior",
    duration: "3 months; extension possible",
    postedDate: "2026-06-01",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/parsleyhealth/jobs/7753967003",
    summary: "Own a defined conversion-rate optimization engagement across acquisition, checkout, and clinical onboarding.",
    expectations: ["Audit and prioritize funnel experiments", "Brief design and engineering and call test results"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["1099 independent contractor role", "Employer benefits are not listed for this engagement"],
    tags: ["Product management", "CRO", "Experimentation", "Healthcare"],
  },
  {
    id: "yor-ai-devops",
    company: "YOR.AI",
    initials: "YA",
    accent: "#f9c74f",
    role: "Part-Time DevOps & Backend Engineer",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Daily communication; listing names 9:01 a.m.–5:01 p.m. Pacific as collaboration hours",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$70–$80 / hour",
    hourlyPayMin: 70,
    hourlyPayMax: 80,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range.",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "~6 weeks through Aug. 15; extension possible",
    postedDate: "2026-06-28",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs/4362035-part-time-devops-backend-engineer",
    summary: "A hands-on 1099 engagement in an existing AI codebase, working directly with the co-founder and lead engineer.",
    expectations: ["Manage infrastructure for production AI systems", "Debug the RAG system and maintain Postgres and vector databases"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["1099 contract", "Employer benefits are not listed", "No equity"],
    tags: ["Python", "DevOps", "RAG", "Postgres"],
  },
  {
    id: "form-ai-engineer",
    company: "Form AI",
    initials: "FA",
    accent: "#5eead4",
    role: "Fractional Software Engineer",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Client-facing work; Central Time preferred; most communication is written",
    scheduleText: "10–20 hrs / week",
    hoursMin: 10,
    hoursMax: 20,
    compensation: "$75–$150 / hour",
    hourlyPayMin: 75,
    hourlyPayMax: 150,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range.",
    workType: "Fractional",
    seniority: "Mid-level",
    duration: "Monthly minimum of 40 hours; scales by agreement",
    postedDate: "2026-05-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs/4163009-software-engineer",
    summary: "A client-facing builder role spanning product scoping, full-stack implementation, integrations, and LLM systems.",
    expectations: ["Scope each engagement with the client", "Ship end-to-end applications and AI workflows"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["1099 contract", "Employer benefits are not listed", "Paid monthly"],
    tags: ["Python", "TypeScript", "React", "Generative AI"],
  },
  {
    id: "cars-bids-data",
    company: "Cars & Bids",
    initials: "CB",
    accent: "#fb7185",
    role: "Senior Data Engineer — Fractional",
    category: "Data",
    location: "Remote · United States",
    collaboration: "Five-hour overlap with Pacific working hours; contractor sets schedule and tools",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$80–$120 / hour",
    hourlyPayMin: 80,
    hourlyPayMax: 120,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range.",
    workType: "Fractional",
    seniority: "Senior",
    duration: "Ongoing monthly retainer",
    postedDate: "2026-07-13",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Indeed",
    sourceUrl: "https://www.indeed.com/viewjob?jk=f9f7455d1778c9b8",
    summary: "The sole dedicated data practitioner owns the stack from ingestion through Snowflake, modeling, inference, and reverse ETL.",
    expectations: ["Own the data stack and its operational health", "Keep pipelines, models, and syncs reliable and cost-efficient"],
    benefitTypes: [],
    benefitDisclosure: "none",
    benefits: ["No company benefits or equity", "Contractor supplies equipment and insurance", "1099/B2B monthly retainer"],
    tags: ["Snowflake", "SQL", "Reverse ETL", "Data quality"],
  },
  {
    id: "dg-data-engineer",
    company: "D&G Support Services",
    initials: "DG",
    accent: "#f0abfc",
    role: "Data Engineer — Part Time",
    category: "Data",
    location: "Remote · United States",
    collaboration: "Government stakeholder work; active Secret clearance required",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "$60–$67 / hour",
    hourlyPayMin: 60,
    hourlyPayMax: 67,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range.",
    workType: "Part-time",
    seniority: "Senior",
    duration: "Not stated",
    postedDate: "2026-07-12",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Migrate Mate",
    sourceUrl: "https://migratemate.co/companies-hiring/d-g-support-services-llc",
    summary: "Connect mission requirements, data strategy, modeling, and architecture roadmaps for defense clients.",
    expectations: ["Develop mission architecture frameworks", "Document systems, data flows, interfaces, and technical risks"],
    benefitTypes: ["Retirement", "Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["401(k), PTO, education reimbursement and profit sharing are listed", "Eligibility thresholds are not stated"],
    tags: ["Systems architecture", "MBSE", "Data flows", "Secret clearance"],
  },
  {
    id: "hii-sentiment-advisor",
    company: "HII Mission Technologies",
    initials: "HI",
    accent: "#b9ef68",
    role: "Military Advisor — Data Science / Sentiment Analysis",
    category: "Data",
    location: "Remote · United States; substantial travel",
    collaboration: "51–75% episodic OCONUS travel; ability to obtain a Secret clearance",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "$90 / hour",
    hourlyPayMin: 90,
    hourlyPayMax: 90,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly rate.",
    workType: "Part-time",
    seniority: "Senior",
    duration: "Not stated",
    postedDate: "2026-07-08",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "DailyRemote",
    sourceUrl: "https://dailyremote.com/remote-job/military-advisor-data-science-sentiment-analysis-part-time-remote-mission-assurance-4-29181-5263063",
    summary: "Deliver sentiment-analysis frameworks, training, data collection, and intelligence products for DoD missions.",
    expectations: ["Design sentiment-analysis frameworks", "Process multi-source data and brief leadership"],
    benefitTypes: ["Healthcare", "Retirement", "Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["Medical, dental and vision choices are listed", "401(k), paid holidays, PTO and tuition reimbursement are listed", "Eligibility thresholds are not stated"],
    tags: ["NLP", "Python", "OSINT", "Data visualization"],
  },
  {
    id: "nadia-care-ux",
    company: "Nadia Care",
    initials: "NC",
    accent: "#7dd3fc",
    role: "Contract UX Researcher",
    category: "Design",
    location: "Remote · Contiguous United States",
    collaboration: "Occasional calls with product and care teams; weekly interviews with members and staff",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "$50–$80 / hour",
    hourlyPayMin: 50,
    hourlyPayMax: 80,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range.",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "~4 months; extension possible",
    postedDate: "2026-07-06",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/nadiacare/jobs/4306881009",
    summary: "A bounded research engagement focused on member interviews, personas, product friction, and early retention signals in maternal healthcare.",
    expectations: ["Design the interview and outreach strategy", "Deliver personas, friction findings, and retention signals"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["The posting describes benefits for full-time employees", "Contract-role eligibility is not stated"],
    tags: ["UX research", "Healthcare", "Interviews", "Personas"],
  },
  {
    id: "serious-development-design",
    company: "Serious Development",
    initials: "SD",
    accent: "#c4b5fd",
    role: "Fractional Product Systems Designer",
    category: "Design",
    location: "Remote · United States",
    collaboration: "Review-heavy role embedded early with PMs and engineers; prototypes and code are the source of truth",
    scheduleText: "20–30 hrs / month",
    hoursMin: null,
    hoursMax: null,
    compensation: "Hourly pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The posting calls the rate competitive but gives no amount.",
    workType: "Fractional",
    seniority: "Senior",
    duration: "Long-term if mutually successful",
    postedDate: "2026-04-15",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Breezy",
    sourceUrl: "https://serious-development.breezy.hr/p/33118b09b763-fractional-product-systems-designer-web-ios-remote-u-s-based",
    summary: "Own system-level product behavior and consistency rather than producing every screen or maintaining Figma parity.",
    expectations: ["Own interaction patterns and reduce UX drift", "Define behavioral standards across web and native iOS"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "Compensation amount is not disclosed"],
    tags: ["Systems design", "iOS", "Angular", "PrimeNG"],
  },
  {
    id: "brainco-it-support",
    company: "Brain Co.",
    initials: "BC",
    accent: "#fe7d62",
    role: "IT Support Engineer — MENA",
    category: "Security",
    location: "On-site · Abu Dhabi or Doha",
    collaboration: "Owns help desk, onboarding, offboarding, access, hardware logistics, and office support",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "Hourly pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer calls compensation competitive but gives no amount.",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "May grow into full-time",
    postedDate: "2026-05-19",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/brainco/9892c2c7-500b-4a59-aca5-b8a78e984bf9",
    summary: "Keep an applied-AI team unblocked while operating access workflows and audit-ready IT controls across MENA offices.",
    expectations: ["Run help desk and employee lifecycle operations", "Own access requests, hardware logistics, and support runbooks"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Flexible part-time hours are listed", "Healthcare and retirement eligibility are not disclosed"],
    tags: ["Okta", "Google Workspace", "SOC 2", "IT support"],
  },
  {
    id: "foundry-analytics-engineer",
    company: "Foundry for Good",
    initials: "FG",
    accent: "#f9c74f",
    role: "Google Analytics Engineer",
    category: "Data",
    location: "Remote · Philippines",
    collaboration: "Async schedule with occasional calls between 9 a.m. and noon Eastern",
    scheduleText: "5–10 hrs / week",
    hoursMin: 5,
    hoursMax: 10,
    compensation: "Hourly pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer confirms hourly pay but gives no amount.",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "Long-term",
    postedDate: "2026-06-02",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/foundry-for-good/3190f63a-dcd0-482b-84d0-456dbd6c8462/",
    summary: "Own GA4, Google Tag Manager, data layers, consent mode, and measurement quality across a portfolio of mission-driven brands.",
    expectations: ["Implement tracking and conversions", "Debug data quality and document measurement setups"],
    benefitTypes: ["Paid time off", "Paid leave"],
    benefitDisclosure: "listed",
    benefits: ["Vacation, sick time, and life leave are prorated for part-time status", "Bereavement and giving programs are listed"],
    tags: ["GA4", "GTM", "Looker Studio", "Data layers"],
  },
  {
    id: "matterworks-product-design",
    company: "Matterworks",
    initials: "MW",
    accent: "#5eead4",
    role: "Product Designer / Senior Product Designer",
    category: "Design",
    location: "Remote · United States",
    collaboration: "Pairs with engineers and designs across a web app, MCP connector, and agentic interfaces",
    scheduleText: "~20 hrs / week",
    hoursMin: 20,
    hoursMax: 20,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish contract compensation.",
    workType: "Contract",
    seniority: "Not specified",
    duration: "3 months; extension or conversion possible",
    postedDate: "2026-05-07",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/matterworks/9b236ffe-94ab-4f63-9605-324600214f91/",
    summary: "Design AI-native scientific software that makes foundation models of biochemical data useful across several product surfaces.",
    expectations: ["Explore, prototype, and polish end-to-end workflows", "Build reusable components and pair through implementation"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Full-time benefits are described", "Contractor eligibility is not stated"],
    tags: ["Product design", "AI interfaces", "Figma", "Prototyping"],
  },
  {
    id: "vitvio-product-designer",
    company: "VitVio",
    initials: "VV",
    accent: "#fb7185",
    role: "Product Designer — AI-Native Design",
    category: "Design",
    location: "Remote · European time zones",
    collaboration: "Remote contract with occasional trips to partner hospitals",
    scheduleText: "Flexible part-time; hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Contract",
    seniority: "Not specified",
    duration: "Through Jan. 2027; reassessed in December",
    postedDate: "2026-05-29",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/vitvio/c82b8a6c-1625-42dd-bf5f-463cb095212e",
    summary: "Design clinical workflow tools from discovery through working prototypes, using AI throughout the design process.",
    expectations: ["Research, prototype, test, and deliver interfaces", "Design for complex surgical and hospital workflows"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["A laptop is provided for the contract", "Employer healthcare and retirement benefits are not listed"],
    tags: ["Product design", "Healthcare", "AI prototyping", "User research"],
  },
  {
    id: "preql-product-designer",
    company: "Preql",
    initials: "PQ",
    accent: "#f0abfc",
    role: "Product Designer",
    category: "Design",
    location: "Remote · New York City",
    collaboration: "Works with product management and technical leadership; initially part-time with room to grow",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Not specified",
    duration: "Initially part-time; may grow",
    postedDate: "2026-01-28",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/preql/889f09fb-8562-436b-9b15-30d7d56caae7/",
    summary: "Shape conversational data-transformation workflows, dashboards, design systems, and onboarding for finance teams.",
    expectations: ["Own end-to-end product design", "Turn complex data operations into clear interfaces"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "The posting is initially part-time but the ATS classifies it as full-time"],
    tags: ["Product design", "Data products", "AI interfaces", "Design systems"],
  },
  {
    id: "pubgenius-software-engineer",
    company: "pubGENIUS",
    initials: "PG",
    accent: "#b9ef68",
    role: "Software Engineer",
    category: "Engineering",
    location: "Remote · UTC ±3 hours",
    collaboration: "Project-based work with a dedicated PM and at least one other developer",
    scheduleText: "Part-time; hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "Project-based",
    postedDate: "2026-06-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Workable",
    sourceUrl: "https://apply.workable.com/pubgenius-1/j/9DD2F70851/",
    summary: "Build Node.js and AWS services, event-driven systems, and APIs for client and internal products.",
    expectations: ["Develop backend services in Node.js and TypeScript", "Design AWS event-driven systems and production APIs"],
    benefitTypes: ["Paid time off", "Paid leave"],
    benefitDisclosure: "listed",
    benefits: ["Paid vacation and sick days are listed", "Fully remote and flexible hours are listed"],
    tags: ["Node.js", "TypeScript", "AWS", "MySQL"],
  },
  {
    id: "swaprail-backend",
    company: "SwapRail",
    initials: "SR",
    accent: "#7dd3fc",
    role: "Backend Engineer",
    category: "Engineering",
    location: "Remote · Global",
    collaboration: "Part-time preferred; works with wallet and front-end teams",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Not specified",
    duration: "Not stated",
    postedDate: "2026-04-14",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/swaprail/3b42b9ac-57d4-4701-bb92-92a08c28e8ef",
    summary: "Build APIs, routing engines, execution services, data pipelines, and observability for a swap platform.",
    expectations: ["Design scalable backend services", "Integrate on-chain and off-chain data sources"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "The role is explicitly listed as part-time"],
    tags: ["TypeScript", "Go", "Rust", "Web3"],
  },
  {
    id: "swaprail-devops",
    company: "SwapRail",
    initials: "SR",
    accent: "#c4b5fd",
    role: "DevOps Engineer",
    category: "Engineering",
    location: "Remote · Global",
    collaboration: "Part-time preferred; supports multi-service and blockchain infrastructure",
    scheduleText: "Part-time; hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Not specified",
    duration: "Not stated",
    postedDate: "2026-04-14",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/swaprail/9c6f0046-27a8-4d51-935b-fbfa4fa319ec",
    summary: "Own cloud infrastructure, CI/CD, observability, reliability, and blockchain-node operations.",
    expectations: ["Build CI/CD and cloud infrastructure", "Operate monitoring, containers, and node reliability"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "The role is explicitly listed as part-time"],
    tags: ["AWS", "GCP", "Docker", "Terraform"],
  },
  {
    id: "widget-problem-design",
    company: "Widget Factory",
    initials: "WF",
    accent: "#fe7d62",
    role: "Problem Design Engineer",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Fully async; each code-review problem typically takes 1–4 hours",
    scheduleText: "0–25 hrs / week",
    hoursMin: 0,
    hoursMax: 25,
    compensation: "$40 / hour",
    hourlyPayMin: 40,
    hourlyPayMax: 40,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly rate; bonus opportunities are also listed.",
    workType: "Part-time",
    seniority: "Entry-level",
    duration: "Long-term flexible work",
    postedDate: "2025-10-28",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/widgetfactory/7602667e-e96a-4333-a1cb-d674f501279f/",
    summary: "Review real-repository coding problems for fairness, clarity, coherence, and test quality for AI training.",
    expectations: ["Trace code-change intent across unfamiliar repositories", "Judge problem and test quality and explain decisions"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Bonus opportunities are listed", "Healthcare and retirement benefits are not disclosed"],
    tags: ["Code review", "Testing", "AI training", "Technical writing"],
  },
  {
    id: "empirical-fractional-cto",
    company: "Empirical",
    initials: "EM",
    accent: "#f9c74f",
    role: "Fractional CTO",
    category: "Leadership",
    location: "Remote · United States or Latin America",
    collaboration: "Executive technology leadership across early- and growth-stage client companies",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay varies by engagement tier",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer says compensation depends on scope and engagement tier.",
    workType: "Fractional",
    seniority: "Senior",
    duration: "Client engagement based",
    postedDate: "2025-05-15",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/empirical/49f39813-394d-4555-9107-c50f37649085",
    summary: "Provide executive technology direction, product and engineering leadership, and scaling guidance to client companies.",
    expectations: ["Set technology and product direction", "Coach teams and improve delivery and architecture"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Contract engagement", "Employer benefits and pay amount are not disclosed"],
    tags: ["Technology strategy", "Engineering leadership", "Architecture", "Startups"],
  },
  {
    id: "zentrix-software-engineer",
    company: "Zentrix LLC",
    initials: "ZX",
    accent: "#5eead4",
    role: "Software Engineer I",
    category: "Engineering",
    location: "Remote · United States",
    collaboration: "Remote part-time team role with code review, testing, and documentation",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Entry-level",
    duration: "Not stated",
    postedDate: "2026-06-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/zentrixx/182d3e6f-cca7-4f4b-b73a-6bbc9df8e699",
    summary: "An early-career software role covering implementation, testing, code review, troubleshooting, and documentation.",
    expectations: ["Design, develop, and test software", "Participate in review and resolve technical issues"],
    benefitTypes: ["Healthcare", "Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["Medical, dental, vision and generous PTO are listed", "The posting describes a full benefits package for the part-time role"],
    tags: ["Python", "Java", "C#", "Testing"],
  },
  {
    id: "3pillar-devsecops",
    company: "3Pillar",
    initials: "3P",
    accent: "#fb7185",
    role: "Senior DevSecOps Engineer — Part Time",
    category: "Security",
    location: "Remote · Mexico",
    collaboration: "Half-time remote role leading security automation and mentoring engineers",
    scheduleText: "Half-time; exact hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Senior",
    duration: "Not stated",
    postedDate: "2026-06-16",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Lever",
    sourceUrl: "https://jobs.lever.co/3pillarglobal/2b838550-f473-445b-a715-64073e415882",
    summary: "Lead security automation, compliant cloud architecture, identity controls, and security program improvements.",
    expectations: ["Architect secure Azure and CI/CD controls", "Lead security automation and mentor engineers"],
    benefitTypes: ["Healthcare", "Paid time off"],
    benefitDisclosure: "listed",
    benefits: ["Major medical insurance and statutory benefits are listed", "Vacation, discretionary time off, and savings options are listed"],
    tags: ["DevSecOps", "Azure", "IAM", "Compliance"],
  },
  {
    id: "sentient-security-fellow",
    company: "Sentient",
    initials: "SE",
    accent: "#f0abfc",
    role: "Security Research Fellow",
    category: "Security",
    location: "Remote · Global",
    collaboration: "Part-time or full-time research role for undergraduate, master's, or PhD students",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Entry-level",
    duration: "Fellowship; term not stated",
    postedDate: "2026-04-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/sentient/6a518b7b-94bc-48bd-9183-65921890bccf",
    summary: "Research trusted execution environments at the intersection of cryptography, hardware security, and open-source AI.",
    expectations: ["Contribute to the Sentient Enclaves Framework", "Research confidential inference and trustless AI evaluation"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["The role is open to students", "Employer benefits and pay are not disclosed"],
    tags: ["Cryptography", "Hardware security", "TEEs", "AI research"],
  },
  {
    id: "jobgether-network-security",
    company: "Confidential via Jobgether",
    initials: "NS",
    accent: "#b9ef68",
    role: "Network Security Consultant",
    category: "Security",
    location: "Remote · United Kingdom / EMEA",
    collaboration: "50% schedule working with product management and AI engineering",
    scheduleText: "50% schedule; exact hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The original listing does not publish compensation.",
    workType: "Contract",
    seniority: "Senior",
    duration: "6 months; extension possible",
    postedDate: "2026-07-14",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Lever / Jobgether",
    sourceUrl: "https://jobs.lever.co/jobgether/f09c367c-0d30-4d58-b055-f0181e7de4b2",
    summary: "Document real-world enterprise network-security workflows to help shape AI-powered security products.",
    expectations: ["Map network-security responsibilities and decisions", "Translate operational expertise into product requirements"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["The hiring company is not named", "Employer benefits are not disclosed"],
    tags: ["Network security", "SASE", "SD-WAN", "Cloud networking"],
  },
  {
    id: "cgs-compliance",
    company: "Contact Government Services",
    initials: "CG",
    accent: "#7dd3fc",
    role: "Information Security Compliance Coordinator",
    category: "Security",
    location: "Remote · United States",
    collaboration: "25 hours each week supporting the Director of Compliance",
    scheduleText: "25 hrs / week",
    hoursMin: 25,
    hoursMax: 25,
    compensation: "≈ $46–$58 / hour",
    hourlyPayMin: 46.15,
    hourlyPayMax: 57.69,
    hourlyPayIsEstimate: true,
    hourlyPayNote: "Calculated from the employer's $60,000–$75,000 annual range ÷ 1,300 hours (25 × 52).",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "May transition to full-time",
    postedDate: "2026-04-06",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Lever",
    sourceUrl: "https://jobs.lever.co/cgsfederal/980a21b0-8d21-44c6-bc61-c6016e460c39",
    summary: "Keep ISO 27001, SOC 2, and CMMC evidence, controls, documentation, and audit activity organized and current.",
    expectations: ["Collect audit evidence and track requests", "Maintain compliance artifacts, logs, and remediation follow-up"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Part-time benefit eligibility is not stated", "The posting may transition to full-time"],
    tags: ["ISO 27001", "SOC 2", "CMMC", "Audit support"],
  },
  {
    id: "bitnomial-weekend-ops",
    company: "Bitnomial",
    initials: "BT",
    accent: "#c4b5fd",
    role: "Weekend Operations Specialist",
    category: "Security",
    location: "Remote · United States, Canada, or Mexico",
    collaboration: "Independent weekend monitoring with escalation to on-call engineers during incidents",
    scheduleText: "Part-time weekend hours; amount not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "$40–$50 / hour",
    hourlyPayMin: 40,
    hourlyPayMax: 50,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated hourly range; the ATS also displays a broader annual field.",
    workType: "Contract",
    seniority: "Not specified",
    duration: "May grow into full-time",
    postedDate: "2026-03-19",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/bitnomial/c39d21f8-a044-488d-b9e3-e7bb311dafb2",
    summary: "Monitor a regulated derivatives exchange on weekends, execute scheduled tasks, and coordinate incident response.",
    expectations: ["Monitor logs, dashboards, and exchange operations", "Escalate incidents and document operational events"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["A computer-equipment stipend is listed", "Healthcare and retirement benefits are not disclosed"],
    tags: ["Operations", "CloudWatch", "Grafana", "Incident response"],
  },
  {
    id: "blacksmith-salesforce-data",
    company: "Blacksmith Agency",
    initials: "BA",
    accent: "#fe7d62",
    role: "Salesforce Data Engineer",
    category: "Data",
    location: "Remote · Location listed as United",
    collaboration: "Part-time support for internal go-to-market operations",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Senior",
    duration: "Not stated",
    postedDate: "2026-04-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/Blacksmith%20Agency/387763ae-b4a9-4741-ac7c-0cf1d6e4d8ee",
    summary: "Own Salesforce lead ingestion, mapping, validation, deduplication, attribution, and cross-system data syncs.",
    expectations: ["Build and maintain Salesforce data pipelines", "Improve CRM data quality and attribution"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed", "The ATS location value is incomplete"],
    tags: ["Salesforce", "ETL", "Data quality", "APIs"],
  },
  {
    id: "maneuver-data-engineer",
    company: "Maneuver Marketing",
    initials: "MM",
    accent: "#f9c74f",
    role: "Data Engineer — Part-Time Option",
    category: "Data",
    location: "Remote · India",
    collaboration: "Consistent availability preferred during Singapore business hours; incident response targets are explicit",
    scheduleText: "15–20 hrs / week",
    hoursMin: 15,
    hoursMax: 20,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Part-time",
    seniority: "Mid-level",
    duration: "Ongoing operational support",
    postedDate: "2026-04-19",
    postedDateIsEstimate: true,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/maneuver-marketing/86c3bb46-db80-4790-8931-42e2d2735678",
    summary: "Operate BigQuery pipelines, monitor reliability, investigate failures, and maintain data security and runbooks.",
    expectations: ["Monitor pipeline freshness and incidents", "Maintain BigQuery performance, controls, and documentation"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["Employer benefits are not disclosed for the part-time option", "Response-time expectations are published"],
    tags: ["BigQuery", "SQL", "ETL", "Data reliability"],
  },
  {
    id: "xai-data-science-tutor",
    company: "xAI",
    initials: "XA",
    accent: "#5eead4",
    role: "Data Science Tutor",
    category: "Data",
    location: "Remote · Global",
    collaboration: "Contractors set their own hours; project scope and time-zone compatibility vary",
    scheduleText: "Typically 10+ hrs / week; no fixed commitment",
    hoursMin: null,
    hoursMax: null,
    compensation: "$45–$75 / hour in the U.S.",
    hourlyPayMin: 45,
    hourlyPayMax: 75,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "Employer-stated range for U.S.-based candidates; international compensation is provided later.",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "Project-based",
    postedDate: "2025-09-30",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Greenhouse",
    sourceUrl: "https://job-boards.greenhouse.io/xai/jobs/4925835007",
    summary: "Apply professional data-science and writing expertise to technical tutoring and model-development projects.",
    expectations: ["Create and evaluate technical data-science material", "Work independently against project deliverables"],
    benefitTypes: ["Healthcare", "Retirement", "Paid leave"],
    benefitDisclosure: "listed",
    benefits: ["Eligible U.S. positions may include health insurance, 401(k), and paid sick leave", "Benefits depend on employment type, location, and jurisdiction"],
    tags: ["Data science", "Technical writing", "AI training", "Python"],
  },
  {
    id: "neurons-ai-product",
    company: "Neurons Lab",
    initials: "NL",
    accent: "#fb7185",
    role: "AI Business Analyst / Product Manager",
    category: "Product",
    location: "Remote · Europe",
    collaboration: "B2B contract with European time-zone collaboration; can be part-time or full-time",
    scheduleText: "Weekly hours not disclosed",
    hoursMin: null,
    hoursMax: null,
    compensation: "Pay not disclosed",
    hourlyPayMin: null,
    hourlyPayMax: null,
    hourlyPayIsEstimate: false,
    hourlyPayNote: "The employer does not publish compensation.",
    workType: "Contract",
    seniority: "Mid-level",
    duration: "Not stated",
    postedDate: "2026-06-16",
    postedDateIsEstimate: false,
    lastVerifiedDate: checked,
    sourceName: "Ashby",
    sourceUrl: "https://jobs.ashbyhq.com/neurons-lab.com/24977ace-b15c-48b1-b973-c2e715a43395",
    summary: "Find high-value AI opportunities, map processes, prototype solutions, and connect implementations to measurable ROI.",
    expectations: ["Lead discovery and build AI business cases", "Map workflows and move prototypes toward production"],
    benefitTypes: [],
    benefitDisclosure: "not-disclosed",
    benefits: ["B2B contract", "Employer benefits and pay are not disclosed"],
    tags: ["Product management", "Business analysis", "LLMs", "Prototyping"],
  },
];
